// Package System Code generated by swaggo/swag. DO NOT EDIT
package System

import "github.com/swaggo/swag"

const docTemplateGlobalInfo = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contests": {
            "get": {
                "description": "获取系统中所有的赛事列表，包括基本信息如赛事ID、名称、状态等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contests"
                ],
                "summary": "获取赛事列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功反回赛事列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Contest"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/contests/{contest_id}": {
            "get": {
                "description": "获取指定赛事详情，包括基础信息与时间范围",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contests"
                ],
                "summary": "获取赛事详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "赛事ID",
                        "name": "contest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回赛事详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Contest"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tracks/detail/{track_id}": {
            "get": {
                "description": "获取指定赛道的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "获取赛道详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "赛道ID",
                        "name": "track_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回赛道详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Track"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tracks/{contest_id}": {
            "get": {
                "description": "获取指定赛事下的所有赛道列表，包括基本信息如赛道ID、名称、状态等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "获取赛道列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "赛事ID",
                        "name": "contest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回赛道列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Track"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Contest": {
            "type": "object",
            "properties": {
                "contestEndDate": {
                    "description": "比赛结束时间，TIMESTAMP",
                    "type": "string"
                },
                "contestID": {
                    "type": "integer"
                },
                "contestIntroduction": {
                    "description": "比赛简介",
                    "type": "string"
                },
                "contestName": {
                    "description": "比赛名称",
                    "type": "string"
                },
                "contestStartDate": {
                    "description": "比赛开始时间，TIMESTAMP",
                    "type": "string"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码，和http状态码剥离，以分离网络和业务",
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "description": "信息。可以是NULL，也可以是成功时返回的结构体，也可以是失败时的错误信息"
                }
            }
        },
        "model.Track": {
            "type": "object",
            "properties": {
                "contestID": {
                    "type": "integer"
                },
                "trackDescription": {
                    "description": "赛道描述",
                    "type": "string"
                },
                "trackID": {
                    "type": "integer"
                },
                "trackName": {
                    "description": "赛道名称",
                    "type": "string"
                },
                "trackSettings": {
                    "description": "赛道设置，存储为JSON格式",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        }
    }
}`

// SwaggerInfoGlobalInfo holds exported Swagger Info so clients can modify it
var SwaggerInfoGlobalInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "全局信息 API",
	Description:      "Ubik 系统全局信息接口文档",
	InfoInstanceName: "GlobalInfo",
	SwaggerTemplate:  docTemplateGlobalInfo,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoGlobalInfo.InstanceName(), SwaggerInfoGlobalInfo)
}
