basePath: /api/v1
definitions:
  model.Contest:
    properties:
      contestEndDate:
        description: 比赛结束日期，精确到分
        type: string
      contestID:
        type: integer
      contestIntroduction:
        description: 比赛简介
        type: string
      contestName:
        description: 比赛名称
        type: string
      contestStartDate:
        description: 比赛开始日期，精确到分
        type: string
    type: object
  model.Response:
    properties:
      code:
        description: 状态码，和http状态码剥离，以分离网络和业务
        example: 200
        type: integer
      msg:
        description: 信息。可以是NULL，也可以是成功时返回的结构体，也可以是失败时的错误信息
    type: object
  model.Track:
    properties:
      contestID:
        type: integer
      trackDescription:
        description: 赛道描述
        type: string
      trackID:
        type: integer
      trackName:
        description: 赛道名称
        type: string
      trackSettings:
        additionalProperties: {}
        description: 赛道设置，存储为JSON格式
        type: object
    type: object
host: localhost:8082
info:
  contact: {}
  description: Ubik 系统全局信息接口文档
  title: 全局信息 API
  version: "1.0"
paths:
  /contests:
    get:
      consumes:
      - application/json
      description: 获取系统中所有的赛事列表，包括基本信息如赛事ID、名称、状态等
      parameters:
      - description: Bearer {access_token}
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功反回赛事列表
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                msg:
                  items:
                    $ref: '#/definitions/model.Contest'
                  type: array
              type: object
      summary: 获取赛事列表
      tags:
      - Contests
  /contests/{contest_id}:
    get:
      consumes:
      - application/json
      description: 获取指定赛事详情，包括基础信息与时间范围
      parameters:
      - description: Bearer {access_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 赛事ID
        in: path
        name: contest_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回赛事详情
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                msg:
                  $ref: '#/definitions/model.Contest'
              type: object
      summary: 获取赛事详情
      tags:
      - Contests
  /tracks/{contest_id}:
    get:
      consumes:
      - application/json
      description: 获取指定赛事下的所有赛道列表，包括基本信息如赛道ID、名称、状态等
      parameters:
      - description: Bearer {access_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 赛事ID
        in: path
        name: contest_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回赛道列表
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                msg:
                  items:
                    $ref: '#/definitions/model.Track'
                  type: array
              type: object
      summary: 获取赛道列表
      tags:
      - Tracks
  /tracks/detail/{track_id}:
    get:
      consumes:
      - application/json
      description: 获取指定赛道的详细信息
      parameters:
      - description: Bearer {access_token}
        in: header
        name: Authorization
        required: true
        type: string
      - description: 赛道ID
        in: path
        name: track_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回赛道详情
          schema:
            allOf:
            - $ref: '#/definitions/model.Response'
            - properties:
                msg:
                  $ref: '#/definitions/model.Track'
              type: object
      summary: 获取赛道详情
      tags:
      - Tracks
swagger: "2.0"
