// Package Admin Code generated by swaggo/swag. DO NOT EDIT
package Admin

import "github.com/swaggo/swag"

const docTemplateAdmin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/authors": {
            "get": {
                "description": "管理员按可选作者名查询作者列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取作者列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "作者名，可选",
                        "name": "author_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "偏移量，默认0",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回条数，默认20，最大100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Author"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/authors/{author_id}": {
            "get": {
                "description": "管理员根据作者ID获取作者详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取作者详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "作者ID",
                        "name": "author_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Author"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "管理员更新指定ID的作者信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新作者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "作者ID",
                        "name": "author_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新后的作者信息",
                        "name": "author",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Author"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Author"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员删除指定ID的作者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除作者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "作者ID",
                        "name": "author_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/contest": {
            "post": {
                "description": "管理员创建新的征文活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建征文活动",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "征文活动信息",
                        "name": "contest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Contest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "活动创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Contest"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/contest/{contest_id}": {
            "put": {
                "description": "管理员更新指定ID的征文活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新征文活动",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "征文活动ID",
                        "name": "contest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新后的征文活动信息",
                        "name": "contest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Contest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "活动更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Contest"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员删除指定ID的征文活动",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除征文活动",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "征文活动ID",
                        "name": "contest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "活动删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "description": "管理员使用用户名和密码登录，成功后返回JWT Token和Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "管理员后台登录",
                "parameters": [
                    {
                        "description": "管理员登录信息",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Admin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/token.ResponseToken"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/refresh": {
            "post": {
                "description": "管理员使用Refresh Token刷新JWT Token，成功后返回新的JWT Token和Refresh Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "刷新管理员JWT Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {refresh_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "刷新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/token.ResponseToken"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/script-flows": {
            "get": {
                "description": "管理员获取脚本流程列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取脚本流程列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ScriptFlow"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "管理员创建脚本流程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建脚本流程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "脚本流程",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ScriptFlow"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptFlow"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/script-flows/mounts": {
            "post": {
                "description": "管理员创建流程挂载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建流程挂载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "挂载信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.FlowMount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.FlowMount"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/script-flows/mounts/{mount_id}": {
            "delete": {
                "description": "管理员删除指定流程挂载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除流程挂载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "挂载ID",
                        "name": "mount_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/script-flows/{flow_id}": {
            "get": {
                "description": "管理员根据流程ID获取脚本流程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取脚本流程详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "流程ID",
                        "name": "flow_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptFlow"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "管理员更新指定脚本流程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新脚本流程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "流程ID",
                        "name": "flow_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新后的流程",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ScriptFlow"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptFlow"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/script-flows/{flow_id}/mounts": {
            "get": {
                "description": "管理员获取指定流程的挂载列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取流程挂载列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "流程ID",
                        "name": "flow_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.FlowMount"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/script-flows/{flow_id}/status": {
            "post": {
                "description": "管理员更新指定流程的启用状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新流程启用状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "流程ID",
                        "name": "flow_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.updateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/script-flows/{flow_id}/steps": {
            "get": {
                "description": "管理员获取指定流程步骤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取流程步骤列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "流程ID",
                        "name": "flow_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.FlowStep"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "管理员替换指定流程的全部步骤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "替换流程步骤",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "流程ID",
                        "name": "flow_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "步骤列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.FlowStep"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/scripts": {
            "get": {
                "description": "管理员获取脚本定义列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取脚本定义列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ScriptDefinition"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "管理员创建脚本定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建脚本定义",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "脚本定义",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ScriptDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptDefinition"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/scripts/{script_id}": {
            "get": {
                "description": "管理员根据脚本ID获取脚本定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取脚本定义详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "脚本ID",
                        "name": "script_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptDefinition"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "管理员更新指定脚本定义",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新脚本定义",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "脚本ID",
                        "name": "script_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新后的脚本定义",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ScriptDefinition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptDefinition"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/scripts/{script_id}/status": {
            "post": {
                "description": "管理员更新指定脚本的启用状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新脚本启用状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "脚本ID",
                        "name": "script_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "状态请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin.updateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/scripts/{script_id}/versions": {
            "get": {
                "description": "管理员获取指定脚本的版本列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取脚本版本列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "脚本ID",
                        "name": "script_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.ScriptVersion"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/scripts/{script_id}/versions/upload": {
            "post": {
                "description": "管理员上传脚本文件并创建新版本",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "上传脚本版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "脚本ID",
                        "name": "script_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "脚本文件",
                        "name": "script_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.ScriptVersion"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/scripts/{script_id}/versions/{version_id}/activate": {
            "post": {
                "description": "管理员激活指定脚本版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "激活脚本版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "脚本ID",
                        "name": "script_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "版本ID",
                        "name": "version_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "激活成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/sub-admins": {
            "get": {
                "description": "仅超级管理员可获取全部子管理员及其权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取子管理员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.SubAdminInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "仅超级管理员可创建子管理员并分配权限，返回临时密码并尝试发送邮件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建子管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "创建子管理员请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateSubAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.SubAdminCreateResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/sub-admins/batch": {
            "post": {
                "description": "支持 JSON({emails:[...]}) 或 text/csv(首列邮箱) 的批量导入，返回每条创建结果与失败原因",
                "consumes": [
                    "application/json",
                    "text/csv"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "批量创建子管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "JSON批量创建请求",
                        "name": "req",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.BatchCreateSubAdminsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建完成",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.BatchCreateSubAdminsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/sub-admins/handover-super": {
            "post": {
                "description": "将超级管理员权限交接给目标管理员，并禁用当前超级管理员",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "超级管理员交接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "交接请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandoverSuperAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "交接成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/sub-admins/{admin_id}": {
            "delete": {
                "description": "仅超级管理员可删除子管理员账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除子管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "子管理员ID",
                        "name": "admin_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/sub-admins/{admin_id}/disable": {
            "post": {
                "description": "仅超级管理员可禁用子管理员账户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "禁用子管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "子管理员ID",
                        "name": "admin_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "禁用成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/sub-admins/{admin_id}/permissions": {
            "put": {
                "description": "仅超级管理员可替换子管理员的权限集合",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新子管理员权限",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "子管理员ID",
                        "name": "admin_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "权限更新请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateSubAdminPermissionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/track": {
            "post": {
                "description": "管理员创建新的赛道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建赛道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "赛道信息",
                        "name": "track",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Track"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "赛道创建成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Track"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/track/{track_id}": {
            "put": {
                "description": "管理员更新指定ID的赛道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新赛道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "赛道ID",
                        "name": "track_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新后的赛道信息",
                        "name": "track",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Track"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "赛道更新成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Track"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员删除指定ID的赛道",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除赛道",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "赛道ID",
                        "name": "track_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "赛道删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/works": {
            "get": {
                "description": "管理员按可选条件查询作品；不传某个参数表示不按该条件过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "统一查询作品列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "赛道ID，可选",
                        "name": "track_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "作品状态，可选",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "作品名，可选",
                        "name": "work_title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "作者名，可选",
                        "name": "author_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "偏移量，默认0",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回条数，默认20，最大100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Work"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/works/{work_id}": {
            "get": {
                "description": "管理员根据作品ID获取作品详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取作品详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "作品ID",
                        "name": "work_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "$ref": "#/definitions/model.Work"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员根据作品ID删除作品及其存储文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "删除作品",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "作品ID",
                        "name": "work_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.Response"
                        }
                    }
                }
            }
        },
        "/admin/works/{work_id}/file": {
            "get": {
                "description": "管理员根据作品ID获取作品文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取作品文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer {access_token}",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "作品ID",
                        "name": "work_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "作品文件",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin.updateStatusRequest": {
            "type": "object",
            "properties": {
                "isEnabled": {
                    "type": "boolean"
                }
            }
        },
        "model.Admin": {
            "type": "object",
            "properties": {
                "adminEmail": {
                    "type": "string"
                },
                "adminID": {
                    "type": "integer"
                },
                "adminName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.Author": {
            "type": "object",
            "properties": {
                "authorEmail": {
                    "type": "string"
                },
                "authorID": {
                    "type": "integer"
                },
                "authorInfos": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "authorName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "penName": {
                    "type": "string"
                }
            }
        },
        "model.BatchCreateSubAdminFailure": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "model.BatchCreateSubAdminsRequest": {
            "type": "object",
            "properties": {
                "emails": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "permissionNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.BatchCreateSubAdminsResponse": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SubAdminCreateResult"
                    }
                },
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BatchCreateSubAdminFailure"
                    }
                }
            }
        },
        "model.Contest": {
            "type": "object",
            "properties": {
                "contestEndDate": {
                    "description": "比赛结束时间，TIMESTAMP",
                    "type": "string"
                },
                "contestID": {
                    "type": "integer"
                },
                "contestIntroduction": {
                    "description": "比赛简介",
                    "type": "string"
                },
                "contestName": {
                    "description": "比赛名称",
                    "type": "string"
                },
                "contestStartDate": {
                    "description": "比赛开始时间，TIMESTAMP",
                    "type": "string"
                }
            }
        },
        "model.CreateSubAdminRequest": {
            "type": "object",
            "properties": {
                "adminEmail": {
                    "type": "string"
                },
                "adminName": {
                    "type": "string"
                },
                "permissionNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.FlowMount": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "eventKey": {
                    "type": "string"
                },
                "flowID": {
                    "type": "integer"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "mountID": {
                    "type": "integer"
                },
                "scope": {
                    "type": "string"
                },
                "targetID": {
                    "type": "integer"
                },
                "targetType": {
                    "type": "string"
                }
            }
        },
        "model.FlowStep": {
            "type": "object",
            "properties": {
                "failureStrategy": {
                    "type": "string"
                },
                "flowID": {
                    "type": "integer"
                },
                "inputTemplate": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "scriptID": {
                    "type": "integer"
                },
                "scriptVersionID": {
                    "type": "integer"
                },
                "stepID": {
                    "type": "integer"
                },
                "stepName": {
                    "type": "string"
                },
                "stepOrder": {
                    "type": "integer"
                },
                "timeoutMs": {
                    "type": "integer"
                }
            }
        },
        "model.HandoverSuperAdminRequest": {
            "type": "object",
            "properties": {
                "newSuperAdminID": {
                    "type": "integer"
                }
            }
        },
        "model.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码，和http状态码剥离，以分离网络和业务",
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "description": "信息。可以是NULL，也可以是成功时返回的结构体，也可以是失败时的错误信息"
                }
            }
        },
        "model.ScriptDefinition": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "interpreter": {
                    "type": "string"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "scriptID": {
                    "type": "integer"
                },
                "scriptKey": {
                    "type": "string"
                },
                "scriptName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ScriptFlow": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "flowID": {
                    "type": "integer"
                },
                "flowKey": {
                    "type": "string"
                },
                "flowName": {
                    "type": "string"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ScriptVersion": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "integer"
                },
                "fileName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "relativePath": {
                    "type": "string"
                },
                "scriptID": {
                    "type": "integer"
                },
                "versionID": {
                    "type": "integer"
                },
                "versionNum": {
                    "type": "integer"
                }
            }
        },
        "model.SubAdminCreateResult": {
            "type": "object",
            "properties": {
                "adminEmail": {
                    "type": "string"
                },
                "adminID": {
                    "type": "integer"
                },
                "adminName": {
                    "type": "string"
                },
                "emailError": {
                    "type": "string"
                },
                "emailSent": {
                    "type": "boolean"
                },
                "tempPassword": {
                    "type": "string"
                }
            }
        },
        "model.SubAdminInfo": {
            "type": "object",
            "properties": {
                "adminEmail": {
                    "type": "string"
                },
                "adminID": {
                    "type": "integer"
                },
                "adminName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "permissionNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Track": {
            "type": "object",
            "properties": {
                "contestID": {
                    "type": "integer"
                },
                "trackDescription": {
                    "description": "赛道描述",
                    "type": "string"
                },
                "trackID": {
                    "type": "integer"
                },
                "trackName": {
                    "description": "赛道名称",
                    "type": "string"
                },
                "trackSettings": {
                    "description": "赛道设置，存储为JSON格式",
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "model.UpdateSubAdminPermissionsRequest": {
            "type": "object",
            "properties": {
                "permissionNames": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.Work": {
            "type": "object",
            "properties": {
                "authorID": {
                    "type": "integer"
                },
                "authorName": {
                    "type": "string"
                },
                "trackID": {
                    "type": "integer"
                },
                "trackName": {
                    "type": "string"
                },
                "workID": {
                    "type": "integer"
                },
                "workInfos": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "workStatus": {
                    "type": "string"
                },
                "workTitle": {
                    "type": "string"
                }
            }
        },
        "token.ResponseToken": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfoAdmin holds exported Swagger Info so clients can modify it
var SwaggerInfoAdmin = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "管理后台 API",
	Description:      "Ubik 系统管理后台服务接口文档",
	InfoInstanceName: "Admin",
	SwaggerTemplate:  docTemplateAdmin,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoAdmin.InstanceName(), SwaggerInfoAdmin)
}
